### ISSUE TITLE
요구사항 확인 및 서비스 기획

### ISSUE THREAD

**Issue by bluebirdxday** [bluebirdxday/SEOB#1]
## Description
> 요구사항에 맞는 서비스를 기획한다.

## To-do
- [] 주제 선정 및 서비스 기획
- [] Figma를 활용한 화면 설계
- [] git commit template 메세지를 정하기
